# Generated by Django 4.1.4 on 2023-01-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ratinag',
            new_name='rating',
        ),
    ]
